sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "12"
  - "10"
before_script:
  - cd test/fixtures/create-react-app && yarn install
script:
  - yarn run test
