sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - test/fixtures/create-react-app/node_modules
node_js:
  - "12"
  - "10"
before_script:
  - cd test/fixtures/create-react-app
  - yarn install
  - cd ../../../
script:
  - yarn run test
